### ISSUE TITLE
Получение токена и работа через Kodi 

### ISSUE THREAD

**Issue by minherc** [MarshalX/yandex-music-token#24]
Получение токена через APK - работает (Телеграм бота правда заблокировали)
При использовании вашего (ошибка, не вашего)) плагина яндекс музыки для Kodi,
после ввода токена выскакивает ошибка в логе коди:

```
**версия плагина:**
2023-10-27 12:02:05.209 T:6784     info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.yandex-music v0.1.6 installed

**код ошибки:**

2023-10-27 12:14:53.332 T:2612  warning <general>: [---] codec: mp3, high_res: False
2023-10-27 12:14:53.332 T:2612  warning <general>: [---] check login token y0_AgAAAAAhA68tAAG8XgAAAA***************************************
2023-10-27 12:14:53.504 T:2612  warning <general>: [---] [Yandex music plugin] authorized: True, mode: None, args: {}
2023-10-27 12:14:53.734 T:2612    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'uid'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 685, in <module>
                                                       main()
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 514, in main
                                                       build_main(authorized, client)
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 222, in build_main
                                                       entry_list += [build_item_playlist(playlist) for playlist in playlists]
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 222, in <listcomp>
                                                       entry_list += [build_item_playlist(playlist) for playlist in playlists]
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 147, in build_item_playlist
                                                       url = build_url({'mode': 'playlist', 'playlist_id': playlist.playlist_id, 'title': playlist.title})
                                                     File "C:\Users\Me\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api\yandex_music\playlist\playlist.py", line 172, in playlist_id
                                                       return f'{self.owner.uid}:{self.kind}'
                                                   AttributeError: 'NoneType' object has no attribute 'uid'
                                                   -->End of Python script error report<--


```

**Информация о коди:**

![image](https://github.com/MarshalX/yandex-music-token/assets/6546280/cadc3abf-b086-4ba8-af18-7e1c6d47cf3a)

ps api яндекс музыки используется ваш, авторизация не проходит, что-то изменилось, при осмотре кода понять как происходит авторизация не получилось..

**Comment by MarshalX** [comment]
Судя по ошибке автор плагина не учел что у плейлиста может не быть поля owner. Может там в целом ошибка вместо плейлиста вернулась. Баг на стороне плагина. Не имею причастия к нему. Создайте issue в их репозитории: https://github.com/Angel777d/kodi.plugin.yandex-music
